<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MasVarietas3Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('sibenih_mas_varietas')->insert([
            ["komoditas_id" => 3, "nama" => "A-1"],
            ["komoditas_id" => 3, "nama" => "A-3"],
            ["komoditas_id" => 3, "nama" => "A-4"],
            ["komoditas_id" => 3, "nama" => "A-5"],
            ["komoditas_id" => 3, "nama" => "A-6"],
            ["komoditas_id" => 3, "nama" => "AS-1"],
            ["komoditas_id" => 3, "nama" => "AS-3"],
            ["komoditas_id" => 3, "nama" => "AS-4"],
            ["komoditas_id" => 3, "nama" => "AS-6"],
            ["komoditas_id" => 3, "nama" => "B 50"],
            ["komoditas_id" => 3, "nama" => "B 52"],
            ["komoditas_id" => 3, "nama" => "B 88"],
            ["komoditas_id" => 3, "nama" => "B 89"],
            ["komoditas_id" => 3, "nama" => "B 99"],
            ["komoditas_id" => 3, "nama" => "Bima 1"],
            ["komoditas_id" => 3, "nama" => "Bima 2 Bantimurung"],
            ["komoditas_id" => 3, "nama" => "Bima 3 Bantimurung"],
            ["komoditas_id" => 3, "nama" => "Bima 4"],
            ["komoditas_id" => 3, "nama" => "Bima 5"],
            ["komoditas_id" => 3, "nama" => "Bima 6"],
            ["komoditas_id" => 3, "nama" => "Bima 7"],
            ["komoditas_id" => 3, "nama" => "Bima 8"],
            ["komoditas_id" => 3, "nama" => "Bima 9"],
            ["komoditas_id" => 3, "nama" => "Bima 10"],
            ["komoditas_id" => 3, "nama" => "Bima 11"],
            ["komoditas_id" => 3, "nama" => "Bima 12 Q"],
            ["komoditas_id" => 3, "nama" => "Bima 13 Q"],
            ["komoditas_id" => 3, "nama" => "Bima 14 Batara"],
            ["komoditas_id" => 3, "nama" => "Bima 15 Sayang"],
            ["komoditas_id" => 3, "nama" => "Bima 16"],
            ["komoditas_id" => 3, "nama" => "Bima 17"],
            ["komoditas_id" => 3, "nama" => "Bima 18"],
            ["komoditas_id" => 3, "nama" => "Bima 20"],
            ["komoditas_id" => 3, "nama" => "Bima Provit A1"],
            ["komoditas_id" => 3, "nama" => "Bima Putih 1"],
            ["komoditas_id" => 3, "nama" => "Bima Putih 2"],
            ["komoditas_id" => 3, "nama" => "Bisi 222"],
            ["komoditas_id" => 3, "nama" => "Bisi 816"],
            ["komoditas_id" => 3, "nama" => "Bisi 818"],
            ["komoditas_id" => 3, "nama" => "Bisi-1"],
            ["komoditas_id" => 3, "nama" => "Bisi-2"],
            ["komoditas_id" => 3, "nama" => "Bisi-3"],
            ["komoditas_id" => 3, "nama" => "Bisi-4"],
            ["komoditas_id" => 3, "nama" => "Bisi-5"],
            ["komoditas_id" => 3, "nama" => "Bisi-6"],
            ["komoditas_id" => 3, "nama" => "Bisi-7"],
            ["komoditas_id" => 3, "nama" => "Bisi-8"],
            ["komoditas_id" => 3, "nama" => "Bisi-9"],
            ["komoditas_id" => 3, "nama" => "Bisi-10"],
            ["komoditas_id" => 3, "nama" => "Bisi-11"],
            ["komoditas_id" => 3, "nama" => "Bisi-12"],
            ["komoditas_id" => 3, "nama" => "Bisi-13"],
            ["komoditas_id" => 3, "nama" => "Bisi-14"],
            ["komoditas_id" => 3, "nama" => "Bisi-15"],
            ["komoditas_id" => 3, "nama" => "Bisi-16"],
            ["komoditas_id" => 3, "nama" => "Bisi-18"],
            ["komoditas_id" => 3, "nama" => "BR 2"],
            ["komoditas_id" => 3, "nama" => "BR 4"],
            ["komoditas_id" => 3, "nama" => "C-1"],
            ["komoditas_id" => 3, "nama" => "C-2"],
            ["komoditas_id" => 3, "nama" => "C-3"],
            ["komoditas_id" => 3, "nama" => "C-4"],
            ["komoditas_id" => 3, "nama" => "C-5"],
            ["komoditas_id" => 3, "nama" => "C-6"],
            ["komoditas_id" => 3, "nama" => "C-7"],
            ["komoditas_id" => 3, "nama" => "C-8"],
            ["komoditas_id" => 3, "nama" => "C-9"],
            ["komoditas_id" => 3, "nama" => "C-10"],
            ["komoditas_id" => 3, "nama" => "CPI-1"],
            ["komoditas_id" => 3, "nama" => "CPI-2"],
            ["komoditas_id" => 3, "nama" => "DK 6818"],
            ["komoditas_id" => 3, "nama" => "DK 6999"],
            ["komoditas_id" => 3, "nama" => "DK 7711"],
            ["komoditas_id" => 3, "nama" => "DK 7722"],
            ["komoditas_id" => 3, "nama" => "DK 85"],
            ["komoditas_id" => 3, "nama" => "DK 95"],
            ["komoditas_id" => 3, "nama" => "DK 979"],
            ["komoditas_id" => 3, "nama" => "DK 9910"],
            ["komoditas_id" => 3, "nama" => "DK-2"],
            ["komoditas_id" => 3, "nama" => "DK-3"],
            ["komoditas_id" => 3, "nama" => "DMI 1"],
            ["komoditas_id" => 3, "nama" => "DMI 2"],
            ["komoditas_id" => 3, "nama" => "DMI 3"],
            ["komoditas_id" => 3, "nama" => "Harmoni 1"],
            ["komoditas_id" => 3, "nama" => "IJK 7"],
            ["komoditas_id" => 3, "nama" => "IPB-4"],
            ["komoditas_id" => 3, "nama" => "IPB-4"],
            ["komoditas_id" => 3, "nama" => "Jambore"],
            ["komoditas_id" => 3, "nama" => "Jaya 1"],
            ["komoditas_id" => 3, "nama" => "Jaya 2"],
            ["komoditas_id" => 3, "nama" => "Jaya 3"],
            ["komoditas_id" => 3, "nama" => "JK 8"],
            ["komoditas_id" => 3, "nama" => "Makmur-1"],
            ["komoditas_id" => 3, "nama" => "Makmur-3"],
            ["komoditas_id" => 3, "nama" => "Makmur-2"],
            ["komoditas_id" => 3, "nama" => "Makmur-4"],
            ["komoditas_id" => 3, "nama" => "MTH-06"],
            ["komoditas_id" => 3, "nama" => "N-37"],
            ["komoditas_id" => 3, "nama" => "N-35"],
            ["komoditas_id" => 3, "nama" => "NK 6226"],
            ["komoditas_id" => 3, "nama" => "NK 6325"],
            ["komoditas_id" => 3, "nama" => "NK 6326"],
            ["komoditas_id" => 3, "nama" => "NK 6645"],
            ["komoditas_id" => 3, "nama" => "NK-11"],
            ["komoditas_id" => 3, "nama" => "NK-22"],
            ["komoditas_id" => 3, "nama" => "NK-33"],
            ["komoditas_id" => 3, "nama" => "NK-55"],
            ["komoditas_id" => 3, "nama" => "NK-66"],
            ["komoditas_id" => 3, "nama" => "NK-77"],
            ["komoditas_id" => 3, "nama" => "NK-81"],
            ["komoditas_id" => 3, "nama" => "NK-82"],
            ["komoditas_id" => 3, "nama" => "NK-88"],
            ["komoditas_id" => 3, "nama" => "NK-99"],
            ["komoditas_id" => 3, "nama" => "NKRI"],
            ["komoditas_id" => 3, "nama" => "NT 10"],
            ["komoditas_id" => 3, "nama" => "NT 104"],
            ["komoditas_id" => 3, "nama" => "NT 105"],
            ["komoditas_id" => 3, "nama" => "P-6"],
            ["komoditas_id" => 3, "nama" => "P-6"],
            ["komoditas_id" => 3, "nama" => "P-7"],
            ["komoditas_id" => 3, "nama" => "P-7"],
            ["komoditas_id" => 3, "nama" => "P-8"],
            ["komoditas_id" => 3, "nama" => "P-8"],
            ["komoditas_id" => 3, "nama" => "P-9"],
            ["komoditas_id" => 3, "nama" => "P-9"],
            ["komoditas_id" => 3, "nama" => "P-10"],
            ["komoditas_id" => 3, "nama" => "P-10Pioneer-1"],
            ["komoditas_id" => 3, "nama" => "P-11"],
            ["komoditas_id" => 3, "nama" => "P-12"],
            ["komoditas_id" => 3, "nama" => "P-13"],
            ["komoditas_id" => 3, "nama" => "P-14"],
            ["komoditas_id" => 3, "nama" => "P-15"],
            ["komoditas_id" => 3, "nama" => "P-16"],
            ["komoditas_id" => 3, "nama" => "P-17"],
            ["komoditas_id" => 3, "nama" => "P-18"],
            ["komoditas_id" => 3, "nama" => "P-19"],
            ["komoditas_id" => 3, "nama" => "P-20"],
            ["komoditas_id" => 3, "nama" => "P-21"],
            ["komoditas_id" => 3, "nama" => "P-22"],
            ["komoditas_id" => 3, "nama" => "P-23"],
            ["komoditas_id" => 3, "nama" => "P-24"],
            ["komoditas_id" => 3, "nama" => "P-25"],
            ["komoditas_id" => 3, "nama" => "P-26"],
            ["komoditas_id" => 3, "nama" => "P-27"],
            ["komoditas_id" => 3, "nama" => "P-28"],
            ["komoditas_id" => 3, "nama" => "P-29"],
            ["komoditas_id" => 3, "nama" => "P-30"],
            ["komoditas_id" => 3, "nama" => "P-31"],
            ["komoditas_id" => 3, "nama" => "PAC-105"],
            ["komoditas_id" => 3, "nama" => "PAC-105S"],
            ["komoditas_id" => 3, "nama" => "PAC-224"],
            ["komoditas_id" => 3, "nama" => "PAC-313"],
            ["komoditas_id" => 3, "nama" => "PAC-339"],
            ["komoditas_id" => 3, "nama" => "PAC-759"],
            ["komoditas_id" => 3, "nama" => "PAC-984"],
            ["komoditas_id" => 3, "nama" => "Pertiwi-1"],
            ["komoditas_id" => 3, "nama" => "Pertiwi-2"],
            ["komoditas_id" => 3, "nama" => "Pertiwi-3"],
            ["komoditas_id" => 3, "nama" => "Pertiwi-5"],
            ["komoditas_id" => 3, "nama" => "Pertiwi-6"],
            ["komoditas_id" => 3, "nama" => "Pintha 01"],
            ["komoditas_id" => 3, "nama" => "Pioneer-1"],
            ["komoditas_id" => 3, "nama" => "Pioneer-2"],
            ["komoditas_id" => 3, "nama" => "Pioneer-2"],
            ["komoditas_id" => 3, "nama" => "Pioneer-3"],
            ["komoditas_id" => 3, "nama" => "Pioneer-3"],
            ["komoditas_id" => 3, "nama" => "Pioneer-4"],
            ["komoditas_id" => 3, "nama" => "Pioneer-4"],
            ["komoditas_id" => 3, "nama" => "Pioneer-5"],
            ["komoditas_id" => 3, "nama" => "Pioneer-5"],
            ["komoditas_id" => 3, "nama" => "R-01"],
            ["komoditas_id" => 3, "nama" => "RK 45"],
            ["komoditas_id" => 3, "nama" => "RK 57"],
            ["komoditas_id" => 3, "nama" => "RK 58"],
            ["komoditas_id" => 3, "nama" => "Semar-1"],
            ["komoditas_id" => 3, "nama" => "Semar-2"],
            ["komoditas_id" => 3, "nama" => "Semar-3"],
            ["komoditas_id" => 3, "nama" => "Semar-4"],
            ["komoditas_id" => 3, "nama" => "Semar-5"],
            ["komoditas_id" => 3, "nama" => "Semar-6"],
            ["komoditas_id" => 3, "nama" => "Semar-8"],
            ["komoditas_id" => 3, "nama" => "Semar-9"],
            ["komoditas_id" => 3, "nama" => "Semar-10"],
            ["komoditas_id" => 3, "nama" => "SHS-1"],
            ["komoditas_id" => 3, "nama" => "SHS-2"],
            ["komoditas_id" => 3, "nama" => "SHS-3"],
            ["komoditas_id" => 3, "nama" => "SHS-4"],
            ["komoditas_id" => 3, "nama" => "SHS-11"],
            ["komoditas_id" => 3, "nama" => "SHS-12"],
            ["komoditas_id" => 3, "nama" => "SHS-022"],
            ["komoditas_id" => 3, "nama" => "SHS-024"],
            ["komoditas_id" => 3, "nama" => "SP 1"],
            ["komoditas_id" => 3, "nama" => "SP 2"],
            ["komoditas_id" => 3, "nama" => "Supra 1"],

        ]);
    }
}
