<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MasVarietas2Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('sibenih_mas_varietas')->insert([
            ["komoditas_id" => 2, "nama" => "Aek Sibundong"],
            ["komoditas_id" => 2, "nama" => "Air Tenggulang"],
            ["komoditas_id" => 2, "nama" => "Alabio"],
            ["komoditas_id" => 2, "nama" => "Anak Daro"],
            ["komoditas_id" => 2, "nama" => "Angke"],
            ["komoditas_id" => 2, "nama" => "Arias"],
            ["komoditas_id" => 2, "nama" => "Asahan"],
            ["komoditas_id" => 2, "nama" => "Atomita 1"],
            ["komoditas_id" => 2, "nama" => "Atomita 2"],
            ["komoditas_id" => 2, "nama" => "Atomita 3"],
            ["komoditas_id" => 2, "nama" => "Atomita 4"],
            ["komoditas_id" => 2, "nama" => "Ayung"],
            ["komoditas_id" => 2, "nama" => "Bahbolon"],
            ["komoditas_id" => 2, "nama" => "Bahbutong"],
            ["komoditas_id" => 2, "nama" => "Banyuasin"],
            ["komoditas_id" => 2, "nama" => "Barito"],
            ["komoditas_id" => 2, "nama" => "Barumun"],
            ["komoditas_id" => 2, "nama" => "Bastari"],
            ["komoditas_id" => 2, "nama" => "Batang Agam"],
            ["komoditas_id" => 2, "nama" => "Batang Anai"],
            ["komoditas_id" => 2, "nama" => "Batang Gadis"],
            ["komoditas_id" => 2, "nama" => "Batang Lembang"],
            ["komoditas_id" => 2, "nama" => "Batang Ombilin"],
            ["komoditas_id" => 2, "nama" => "Batang Pane"],
            ["komoditas_id" => 2, "nama" => "Batang Piaman"],
            ["komoditas_id" => 2, "nama" => "Batang Sumani"],
            ["komoditas_id" => 2, "nama" => "Batanghari"],
            ["komoditas_id" => 2, "nama" => "Batutegi"],
            ["komoditas_id" => 2, "nama" => "Bengawan Solo"],
            ["komoditas_id" => 2, "nama" => "Bestari"],
            ["komoditas_id" => 2, "nama" => "Bogowonto"],
            ["komoditas_id" => 2, "nama" => "Bondoyudo"],
            ["komoditas_id" => 2, "nama" => "Brantas"],
            ["komoditas_id" => 2, "nama" => "Buyung"],
            ["komoditas_id" => 2, "nama" => "C-22"],
            ["komoditas_id" => 2, "nama" => "C4-63 gb"],
            ["komoditas_id" => 2, "nama" => "Caredek Merah"],
            ["komoditas_id" => 2, "nama" => "Cekau Pelalawan"],
            ["komoditas_id" => 2, "nama" => "Celebes-1"],
            ["komoditas_id" => 2, "nama" => "Cenranae"],
            ["komoditas_id" => 2, "nama" => "Ciapus"],
            ["komoditas_id" => 2, "nama" => "Cibodas"],
            ["komoditas_id" => 2, "nama" => "Cibogo"],
            ["komoditas_id" => 2, "nama" => "Cigeulis"],
            ["komoditas_id" => 2, "nama" => "Ciherang"],
            ["komoditas_id" => 2, "nama" => "Cikapundung"],
            ["komoditas_id" => 2, "nama" => "Cilamaya Muncul"],
            ["komoditas_id" => 2, "nama" => "Ciliwung"],
            ["komoditas_id" => 2, "nama" => "Cilosari"],
            ["komoditas_id" => 2, "nama" => "Cimandiri"],
            ["komoditas_id" => 2, "nama" => "Cimanuk"],
            ["komoditas_id" => 2, "nama" => "Cimelati"],
            ["komoditas_id" => 2, "nama" => "Cipunegara"],
            ["komoditas_id" => 2, "nama" => "Cirata"],
            ["komoditas_id" => 2, "nama" => "Cisadane"],
            ["komoditas_id" => 2, "nama" => "Cisanggarung"],
            ["komoditas_id" => 2, "nama" => "Cisantana"],
            ["komoditas_id" => 2, "nama" => "Cisokan"],
            ["komoditas_id" => 2, "nama" => "Citanduy"],
            ["komoditas_id" => 2, "nama" => "Citarum"],
            ["komoditas_id" => 2, "nama" => "Clasem"],
            ["komoditas_id" => 2, "nama" => "Clujung"],
            ["komoditas_id" => 2, "nama" => "Conde"],
            ["komoditas_id" => 2, "nama" => "Danau Atas"],
            ["komoditas_id" => 2, "nama" => "Danau Bawah"],
            ["komoditas_id" => 2, "nama" => "Danau Gaung"],
            ["komoditas_id" => 2, "nama" => "Danau Tempe"],
            ["komoditas_id" => 2, "nama" => "Dendang"],
            ["komoditas_id" => 2, "nama" => "Diah Suci"],
            ["komoditas_id" => 2, "nama" => "Digul"],
            ["komoditas_id" => 2, "nama" => "Dodokan"],
            ["komoditas_id" => 2, "nama" => "Fatmawati"],
            ["komoditas_id" => 2, "nama" => "Gajah Mungkur"],
            ["komoditas_id" => 2, "nama" => "Gilirang"],
            ["komoditas_id" => 2, "nama" => "Indragiri"],
            ["komoditas_id" => 2, "nama" => "Inpago 1 SHS"],
            ["komoditas_id" => 2, "nama" => "Inpago 2 SHS"],
            ["komoditas_id" => 2, "nama" => "Inpago 3 SHS"],
            ["komoditas_id" => 2, "nama" => "Inpago 4"],
            ["komoditas_id" => 2, "nama" => "Inpago 5"],
            ["komoditas_id" => 2, "nama" => "Inpago 6"],
            ["komoditas_id" => 2, "nama" => "Inpago 7"],
            ["komoditas_id" => 2, "nama" => "Inpago 8"],
            ["komoditas_id" => 2, "nama" => "Inpago 9"],
            ["komoditas_id" => 2, "nama" => "Inpago LIPI Go 1"],
            ["komoditas_id" => 2, "nama" => "Inpago LIPI Go 2"],
            ["komoditas_id" => 2, "nama" => "Inpago Unram 1"],
            ["komoditas_id" => 2, "nama" => "Inpago Unsoed 1"],
            ["komoditas_id" => 2, "nama" => "Inpara 1"],
            ["komoditas_id" => 2, "nama" => "Inpara 2"],
            ["komoditas_id" => 2, "nama" => "Inpara 3"],
            ["komoditas_id" => 2, "nama" => "Inpara 4"],
            ["komoditas_id" => 2, "nama" => "Inpara 5"],
            ["komoditas_id" => 2, "nama" => "Inpara 6"],
            ["komoditas_id" => 2, "nama" => "Inpara 7"],
            ["komoditas_id" => 2, "nama" => "Inpara IPB Kapuas 7R"],
            ["komoditas_id" => 2, "nama" => "Inpari 1"],
            ["komoditas_id" => 2, "nama" => "Inpari 2"],
            ["komoditas_id" => 2, "nama" => "Inpari 3"],
            ["komoditas_id" => 2, "nama" => "Inpari 4"],
            ["komoditas_id" => 2, "nama" => "Inpari 5"],
            ["komoditas_id" => 2, "nama" => "Inpari 6 JETE"],
            ["komoditas_id" => 2, "nama" => "Inpari 7 Lanrang"],
            ["komoditas_id" => 2, "nama" => "Inpari 8"],
            ["komoditas_id" => 2, "nama" => "Inpari 9 Elo"],
            ["komoditas_id" => 2, "nama" => "Inpari 10 Laeya"],
            ["komoditas_id" => 2, "nama" => "Inpari 11"],
            ["komoditas_id" => 2, "nama" => "Inpari 12"],
            ["komoditas_id" => 2, "nama" => "Inpari 12"],
            ["komoditas_id" => 2, "nama" => "Inpari 13"],
            ["komoditas_id" => 2, "nama" => "Inpari 14 Pakuan"],
            ["komoditas_id" => 2, "nama" => "Inpari 15"],
            ["komoditas_id" => 2, "nama" => "Inpari 15 Parahyangan"],
            ["komoditas_id" => 2, "nama" => "Inpari 16 Pasundan"],
            ["komoditas_id" => 2, "nama" => "Inpari 17"],
            ["komoditas_id" => 2, "nama" => "Inpari 18"],
            ["komoditas_id" => 2, "nama" => "Inpari 19"],
            ["komoditas_id" => 2, "nama" => "Inpari 20"],
            ["komoditas_id" => 2, "nama" => "Inpari 21 Batipuah"],
            ["komoditas_id" => 2, "nama" => "Inpari 22"],
            ["komoditas_id" => 2, "nama" => "Inpari 23 Bantul"],
            ["komoditas_id" => 2, "nama" => "Inpari 24 Gabusan"],
            ["komoditas_id" => 2, "nama" => "Inpari 25 Opak Jawa"],
            ["komoditas_id" => 2, "nama" => "Inpari 26"],
            ["komoditas_id" => 2, "nama" => "Inpari 27"],
            ["komoditas_id" => 2, "nama" => "Inpari 30 Ciherang Sub 1"],
            ["komoditas_id" => 2, "nama" => "Inpari Blas"],
            ["komoditas_id" => 2, "nama" => "Inpari HDB"],
            ["komoditas_id" => 2, "nama" => "Inpari Mugibat"],
            ["komoditas_id" => 2, "nama" => "Inpari Sudenuk"],
            ["komoditas_id" => 2, "nama" => "Inparti 28 Kerinci"],
            ["komoditas_id" => 2, "nama" => "Inparti 29 Rendaman"],
            ["komoditas_id" => 2, "nama" => "IPB 1R Dadahup"],
            ["komoditas_id" => 2, "nama" => "IPB 2R Bakumpai"],
            ["komoditas_id" => 2, "nama" => "IPB 35"],
            ["komoditas_id" => 2, "nama" => "IPB 45"],
            ["komoditas_id" => 2, "nama" => "IPB Baltola 5R"],
            ["komoditas_id" => 2, "nama" => "IPB Baltola 6R"],
            ["komoditas_id" => 2, "nama" => "IR 42"],
            ["komoditas_id" => 2, "nama" => "IR 46"],
            ["komoditas_id" => 2, "nama" => "IR 48"],
            ["komoditas_id" => 2, "nama" => "IR 64"],
            ["komoditas_id" => 2, "nama" => "IR 65"],
            ["komoditas_id" => 2, "nama" => "IR 66"],
            ["komoditas_id" => 2, "nama" => "IR 68"],
            ["komoditas_id" => 2, "nama" => "IR 70"],
            ["komoditas_id" => 2, "nama" => "IR 72"],
            ["komoditas_id" => 2, "nama" => "IR 74"],
            ["komoditas_id" => 2, "nama" => "Jangkok"],
            ["komoditas_id" => 2, "nama" => "Jatiluhur"],
            ["komoditas_id" => 2, "nama" => "Junjuang"],
            ["komoditas_id" => 2, "nama" => "Kahayan"],
            ["komoditas_id" => 2, "nama" => "Kalimas"],
            ["komoditas_id" => 2, "nama" => "Kalimutu"],
            ["komoditas_id" => 2, "nama" => "Kapuas"],
            ["komoditas_id" => 2, "nama" => "Karya Pelalawan"],
            ["komoditas_id" => 2, "nama" => "Ketonggo"],
            ["komoditas_id" => 2, "nama" => "Klara"],
            ["komoditas_id" => 2, "nama" => "Konawe"],
            ["komoditas_id" => 2, "nama" => "Krueng Aceh"],
            ["komoditas_id" => 2, "nama" => "Kuriak Kusuik"],
            ["komoditas_id" => 2, "nama" => "Lalan"],
            ["komoditas_id" => 2, "nama" => "Lambur"],
            ["komoditas_id" => 2, "nama" => "Lariang"],
            ["komoditas_id" => 2, "nama" => "Laut Tawar"],
            ["komoditas_id" => 2, "nama" => "Lematang"],
            ["komoditas_id" => 2, "nama" => "Limboto"],
            ["komoditas_id" => 2, "nama" => "Logawa"],
            ["komoditas_id" => 2, "nama" => "Luk Ulo"],
            ["komoditas_id" => 2, "nama" => "Lusi"],
            ["komoditas_id" => 2, "nama" => "Mahakam"],
            ["komoditas_id" => 2, "nama" => "Mandel Handayani"],
            ["komoditas_id" => 2, "nama" => "Maninjau"],
            ["komoditas_id" => 2, "nama" => "Margasari"],
            ["komoditas_id" => 2, "nama" => "Maros"],
            ["komoditas_id" => 2, "nama" => "Martapura"],
            ["komoditas_id" => 2, "nama" => "Mayang"],
            ["komoditas_id" => 2, "nama" => "Mekongga"],
            ["komoditas_id" => 2, "nama" => "Memberamo"],
            ["komoditas_id" => 2, "nama" => "Mendawak"],
            ["komoditas_id" => 2, "nama" => "Meraoke"],
            ["komoditas_id" => 2, "nama" => "Mira-1"],
            ["komoditas_id" => 2, "nama" => "Musi"],
            ["komoditas_id" => 2, "nama" => "Nagara"],
            ["komoditas_id" => 2, "nama" => "Pak Tiwl 1"],
            ["komoditas_id" => 2, "nama" => "Pak Tiwi 2"],
            ["komoditas_id" => 2, "nama" => "Pandan Wangi"],
            ["komoditas_id" => 2, "nama" => "Pandanputri"],
            ["komoditas_id" => 2, "nama" => "Pare Wangi"],
            ["komoditas_id" => 2, "nama" => "PB 5"],
            ["komoditas_id" => 2, "nama" => "PB 20"],
            ["komoditas_id" => 2, "nama" => "PB 26"],
            ["komoditas_id" => 2, "nama" => "PB 28"],
            ["komoditas_id" => 2, "nama" => "PB 30"],
            ["komoditas_id" => 2, "nama" => "PB 32"],
            ["komoditas_id" => 2, "nama" => "PB 36"],
            ["komoditas_id" => 2, "nama" => "PB 38"],
            ["komoditas_id" => 2, "nama" => "PB 42"],
            ["komoditas_id" => 2, "nama" => "PB 50"],
            ["komoditas_id" => 2, "nama" => "PB 52"],
            ["komoditas_id" => 2, "nama" => "PB 54"],
            ["komoditas_id" => 2, "nama" => "PB 56"],
            ["komoditas_id" => 2, "nama" => "Pelita I-1"],
            ["komoditas_id" => 2, "nama" => "Pelita I-2"],
            ["komoditas_id" => 2, "nama" => "Pepe"],
            ["komoditas_id" => 2, "nama" => "Porong"],
            ["komoditas_id" => 2, "nama" => "Poso"],
            ["komoditas_id" => 2, "nama" => "Progo"],
            ["komoditas_id" => 2, "nama" => "Punggur"],
            ["komoditas_id" => 2, "nama" => "Ranau"],
            ["komoditas_id" => 2, "nama" => "Rojolele"],
            ["komoditas_id" => 2, "nama" => "Sadang"],
            ["komoditas_id" => 2, "nama" => "Saganggam Panuah"],
            ["komoditas_id" => 2, "nama" => "Sarinah"],
            ["komoditas_id" => 2, "nama" => "Segreng Handayani"],
            ["komoditas_id" => 2, "nama" => "Sei Lilin"],
            ["komoditas_id" => 2, "nama" => "Semeru"],
            ["komoditas_id" => 2, "nama" => "Sentani"],
            ["komoditas_id" => 2, "nama" => "Serayu"],
            ["komoditas_id" => 2, "nama" => "Setail"],
            ["komoditas_id" => 2, "nama" => "Siak Raya"],
            ["komoditas_id" => 2, "nama" => "Siam Mutiara"],
            ["komoditas_id" => 2, "nama" => "Siam Saba"],
            ["komoditas_id" => 2, "nama" => "Silugonggo"],
            ["komoditas_id" => 2, "nama" => "Singkarak"],
            ["komoditas_id" => 2, "nama" => "Singkil"],
            ["komoditas_id" => 2, "nama" => "Sintanur"],
            ["komoditas_id" => 2, "nama" => "Situ Bagendit"],
            ["komoditas_id" => 2, "nama" => "Situ Patenggang"],
            ["komoditas_id" => 2, "nama" => "Situgintung"],
            ["komoditas_id" => 2, "nama" => "Suluttan Unsrat 2"],
            ["komoditas_id" => 2, "nama" => "Suluttan Unsrat 21"],
            ["komoditas_id" => 2, "nama" => "Sunggal"],
            ["komoditas_id" => 2, "nama" => "Tajum"],
            ["komoditas_id" => 2, "nama" => "Tapus"],
            ["komoditas_id" => 2, "nama" => "Tondano"],
            ["komoditas_id" => 2, "nama" => "Towuti"],
            ["komoditas_id" => 2, "nama" => "Tukad Balian"],
            ["komoditas_id" => 2, "nama" => "Tukad Petanu"],
            ["komoditas_id" => 2, "nama" => "Tukad Unda"],
            ["komoditas_id" => 2, "nama" => "Tuntang"],
            ["komoditas_id" => 2, "nama" => "Walanae"],
            ["komoditas_id" => 2, "nama" => "Way Apo Buru"],
            ["komoditas_id" => 2, "nama" => "Way Rarem"],
            ["komoditas_id" => 2, "nama" => "Way Seputih"],
            ["komoditas_id" => 2, "nama" => "Wera"],
            ["komoditas_id" => 2, "nama" => "Widas"],
            ["komoditas_id" => 2, "nama" => "Winongo"],
            ["komoditas_id" => 2, "nama" => "Woyla"],
            ["komoditas_id" => 2, "nama" => "Yuwono"],
            ["komoditas_id" => 2, "nama" => "Lokal"],
        ]);
    }
}
